# This docker-compose file was gathered from the tutorial 5 lecture slides
version: '2'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=8080
    command:
      sh -c 'npm i && node server.js'